version: '3'

services:

  db-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "321654987"
    ports:
      - "5432:5432"
    networks:
      - network-postgres
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "farias.softwares@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "321654987"
    ports:
      - "5555:80"
    depends_on:
      - db-postgres
    networks:
      - network-postgres

networks: 
  network-postgres:
    driver: bridge
  
